server:
  port: 8088
  servlet:
    context-path: /

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: goodluck-checkin-service
  cloud:
    nacos:
      discovery:
        enabled: false
        metadata:
          management:
            context-path: /${server.servlet.context-path}/actuator
        server-addr: nacos-dev.goodluck.net:80



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    root: info
    com.netflix.config: debug
  config: classpath:logback-custom.xml


#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.goodluck.checkin.domain.*.model
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: is_delete # set deleted logicDelete
#      logic-delete-value: 1 # deleted
#      logic-not-delete-value: 0 # exist
#    banner: false


swagger:
  enabled: true
  scan-package: com.goodluck.checkin

